name: Build Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Set up OpenWrt 24
        run: |
          sudo apt-get install -y build-essential
          git clone -b v24.03.0-rc1 https://git.openwrt.org/openwrt/openwrt.git
          cp -r openwrt/package/myfilter openwrt/package/
      
      - name: Compile
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install myfilter
          make defconfig
          make package/myfilter/compile -j16
